title: Weddings With Anna
email: info@weddingswithanna.com
description: DJ and live band for the best wedding experience in Cincinnati and Northern Kentucky.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://weddingswithanna.com" # the base hostname & protocol for your site, e.g. http://example.com
image: "https://weddingswithanna.com/assets/images/anna-2x.jpg"
github_username:  lukemoderwell

# Build settings
markdown: kramdown
permalink: pretty

# Asset Pipeline
assets:
  source_maps: false # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true # true on JEKYLL_ENV=production
  gzip: true
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  caching:
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
    enabled: true
  sources:
    - assets/css
    - assets/js
    - assets/images


exclude: [package.json, yarn.lock, Gemfile, Gemfile.lock, node_modules, README.md, assets/css]

collections_dir: collections

collections:
  audio:
    output: false
  faqs:
    output: false
