title: Weddings With Anna
email: info@weddingswithanna.com
description: DJ and live band for the best wedding experience in Cincinnati.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://weddingswithanna.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  lukemoderwell

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: assets/css
  style: compact

exclude: [package.json, yarn.lock, Gemfile, Gemfile.lock, node_modules]

collections_dir: collections

collections:
  audio:
    output: false
  faqs:
    output: false
